"""Original prose from Vignettes/02_convergence_and_pooling/vignette.html."""

from __future__ import annotations

import json
from pathlib import Path

_ROOT = Path(__file__).resolve().parents[2]
_PROSE = _ROOT / "Vignettes" / "02_convergence_and_pooling" / "vignette_prose.json"

AUTHORS = "Gerko Vink and Stef van Buuren"
SERIES_LABEL = "Vignette 2 of 6"
TITLE = "Algorithmic convergence and inference pooling"

STEP_TITLES: dict[int, str] = {
    1: "Vary the number of imputations.",
    2: "Change the predictor matrix",
    3: "Inspect the convergence of the algorithm",
    4: "Change the imputation method",
    5: "Extend the number of iterations",
    6: "Further diagnostic checking. Use function `stripplot()`.",
    7: "Perform the following regression analysis on the multiply imputed data. Store the solution in object `fit`.",
    8: "Pool the analyses from object `fit`.",
}

N1_BEFORE = (
    "The number of imputed data sets can be specified by the `m = ...` argument. "
    "For example, to create just three imputed data sets, specify"
)

N2_BEFORE_PRED = (
    "The predictor matrix is a square matrix that specifies the variables that are used "
    "to impute each incomplete variable. Let us have a look at the predictor matrix that was used"
)
N2_AFTER_PRED = (
    "Each variable in the data has a row and a column in the predictor matrix. A value `1` "
    "indicates that the column variable was used to impute the row variable. For example, the `1` "
    "at entry `[bmi, age]` indicates that variable `age` was used to impute the incomplete "
    "variable `bmi`. Note that the diagonal is zero because a variable is not allowed to impute "
    "itself. The row of `age` contains all zeros because there were no missing values in `age`. "
    "`mice` gives you complete control over the predictor matrix, enabling you to choose your own "
    "predictor relations. This can be very useful, for example, when you have many variables or "
    "when you have clear ideas or prior knowledge about relations in the data at hand. You can use "
    "`mice()` to give you the initial predictor matrix, and change it afterwards, without running "
    "the algorithm. This can be done by typing"
)
N2_AFTER_INI = (
    "The object `pred` contains the predictor matrix from an initial run of `mice` with zero "
    "iterations, specified by `maxit = 0`. Altering the predictor matrix and returning it to the "
    "mice algorithm is very simple. For example, the following code removes the variable `hyp` "
    "from the set of predictors, but still leaves it to be predicted by the other variables."
)
N2_AFTER_MOD = "Use your new predictor matrix in `mice()` as follows"
N2_BEFORE_QUICK = (
    "There is a special function called `quickpred()` for a quick selection procedure of predictors, "
    "which can be handy for datasets containing many variables. See `?quickpred` for more info. "
    "Selecting predictors according to data relations with a minimum correlation of ρ = .30 can be done by"
)
N2_AFTER_QUICK = (
    "For large predictor matrices, it can be useful to export them to Microsoft Excel for easier "
    "configuration (e.g. see the `xlsx` package for easy exporting and importing of Excel files)."
)

N3_BEFORE = (
    "The `mice()` function implements an iterative Markov Chain Monte Carlo type of algorithm. "
    "Let us have a look at the trace lines generated by the algorithm to study convergence:"
)
N3_AFTER_PLOT = (
    "The plot shows the mean (left) and standard deviation (right) of the imputed values only. "
    "In general, we would like the streams to intermingle and be free of any trends at the later iterations."
)
N3_BEFORE_SEED = (
    "The algorithm uses random sampling, and therefore, the results will be (perhaps slightly) "
    "different if we repeat the imputations with different seeds. In order to get exactly the same "
    "result, use the `seed` argument"
)
N3_AFTER_SEED = (
    "where `123` is some arbitrary number that you can choose yourself. Rerunning this command "
    "will always yields the same imputed values."
)

N4_BEFORE_METH = (
    "For each column, the algorithm requires a specification of the imputation method. "
    "To see which method was used by default:"
)
N4_AFTER_METH = (
    "The variable `age` is complete and therefore not imputed, denoted by the `\"\"` empty string. "
    "The other variables have method `pmm`, which stands for *predictive mean matching*, the default "
    "in `mice` for numerical and integer data. In reality, the data are better described a as mix of "
    "numerical and categorical data. Let us take a look at the `nhanes2` data frame"
)
N4_BEFORE_STR = "and the structure of the data frame"
N4_AFTER_STR = (
    "Variable `age` consists of 3 age categories, while variable `hyp` is binary. The `mice()` "
    "function takes these properties automatically into account. Impute the `nhanes2` dataset"
)
N4_AFTER_METH2 = (
    "Notice that `mice` has set the imputation method for variable `hyp` to `logreg`, which implements "
    "multiple imputation by *logistic regression*."
)
N4_BEFORE_METHODS = "An up-to-date overview of the methods in mice can be found by"
N4_AFTER_METHODS = (
    "Let us change the imputation method for `bmi` to Bayesian normal linear regression imputation"
)
N4_AFTER_NORM = "and run the imputations again."
N4_BEFORE_PLOT = "We may now again plot trace lines to study convergence"

N5_BEFORE = (
    "Though using just five iterations (the default) often works well in practice, we need to extend "
    "the number of iterations of the `mice` algorithm to confirm that there is no trend and that the "
    "trace lines intermingle well. We can increase the number of iterations to 40 by running 35 additional "
    "iterations using the `mice.mids()` function."
)

N6_BEFORE = (
    "Generally, one would prefer for the imputed data to be plausible values, i.e. values that could "
    "have been observed if they had not been missing. In order to form an idea about plausibility, one "
    "may check the imputations and compare them against the observed values. If we are willing to assume "
    "that the data are missing completely at random (MCAR), then the imputations should have the same "
    "distribution as the observed data. In general, distributions may be different because the missing "
    "data are MAR (or even MNAR). However, very large discrepancies need to be screened. Let us plot the "
    "observed and imputed data of `chl` by"
)
N6_AFTER_STRIP = (
    "The convention is to plot observed data in blue and the imputed data in red. The figure graphs the "
    "data values of `chl` before and after imputation. Since the PMM method draws imputations from the "
    "observed data, imputed values have the same gaps as in the observed data, and are always within the "
    "range of the observed data. The figure indicates that the distributions of the imputed and the "
    "observed values are similar. The observed data have a particular feature that, for some reason, the "
    "data cluster around the value of 187. The imputations reflect this feature, and are close to the data. "
    "Under MCAR, univariate distributions of the observed and imputed data are expected to be identical. "
    "Under MAR, they can be different, both in location and spread, but their multivariate distribution "
    "is assumed to be identical. There are many other ways to look at the imputed data."
)
N6_BEFORE_STRIP2 = (
    "The following command creates a simpler version of the graph from the previous step and adds the "
    "plot for `bmi`."
)
N6_AFTER_STRIP2 = (
    "Remember that `bmi` was imputed by Bayesian linear regression and (the range of) imputed values "
    "may therefore be different than observed values."
)

N7_FORMULA = (
    "Regression model on each completed dataset:\n\n"
    "bmi = β₀ + β₁ chl + ε"
)
N7_AFTER_FIT = (
    "The `fit` object contains the regression summaries for each data set. The new object `fit` is "
    "actually of class `mira` (*multiply imputed repeated analyses*)."
)
N7_BEFORE_LS = "Use the `ls()` function to what out what is in the object."
N7_BEFORE_A2 = (
    "Suppose we want to find the regression model fitted to the second imputed data set. It can be found as"
)

N8_BEFORE = "Pooling the repeated regression analyses can be done simply by typing"
N8_AFTER = (
    "which gives the relevant pooled regression coefficients and parameters, as well as the fraction of "
    "information about the coefficients missing due to nonresponse (`fmi`) and the proportion of the "
    "variation attributable to the missing data (`lambda`). The pooled fit object is of class `mipo`, "
    "which stands for *multiply imputed pooled object*."
)
N8_AFTER_SCALAR = (
    "`mice` is able to pool many analyses from a variety of packages for you, as long as the functions "
    "adhere to the `coef` method convention in R. For flexibility and in order to run custom pooling "
    "functions, mice also incorporates a function `pool.scalar()` which pools univariate estimates of "
    "*m* repeated complete data analysis conform Rubin's pooling rules (Rubin, 1987, paragraph 3.1)"
)


def load_intro() -> str:
    data = json.loads(_PROSE.read_text(encoding="utf-8"))
    intro = data["intro"]
    cut = intro.find("**1. Vary")
    return intro[:cut].strip() if cut >= 0 else intro


def load_step_title(num: int) -> str:
    return STEP_TITLES[num]
